-- Example:
--   require("atlas").setup({
--     providers = {
--       ---@type AtlasBitbucketConfig
--       bitbucket = {
--         user  = vim.env.BITBUCKET_USER,
--         token = vim.env.BITBUCKET_TOKEN,
--         cache_ttl = 300,
--       },
--     },
--     pulls = {
--       ---@type AtlasBitbucketPullsConfig
--       bitbucket = {
--         views = {
--           {
--             name = "All",
--             key  = "1",
--             -- https://developer.atlassian.com/cloud/bitbucket/rest/#filter-and-sort-api-objects
--             search = "repo:acme/core project:acme/WEB",
--           },
--           {
--             name = "Authored",
--             key  = "2",
--             layout = "compact",
--             search = 'project:acme/CORE author.nickname = "my-name"',
--           },
--         },
--         bookmarks = {
--           -- key   = "S",      -- default
--           -- label = "Search", -- default
--           items = {
--             ["Core"] = {
--               layout = "grouped",
--               search = 'repo:acme/standalone project:acme/CORE title ~ "core"',
--             },
--           },
--         },
--       },
--     },
--   })

---@class AtlasBitbucketViewConfig : AtlasPullsViewConfig

---@class AtlasBitbucketBookmarkConfig : AtlasPullsBookmarkConfig

---@class AtlasBitbucketBookmarksConfig
---@field key string|nil    -- default "S"
---@field label string|nil  -- default "Search"
---@field items table<string, string|AtlasBitbucketBookmarkConfig>|nil

---@class AtlasBitbucketPullsConfig
---@field views AtlasBitbucketViewConfig[]|nil
---@field bookmarks AtlasBitbucketBookmarksConfig|nil
