---@class AtlasGitHubConfig
---@field hostname string|nil GitHub hostname; defaults to GH_HOST, then github.com.
---@field cache_ttl number|nil Cache lifetime in seconds. Set to 0 to disable caching.
