---@class AtlasJiraConfig
---@field base_url string
---@field email string|nil Required for basic authentication.
---@field token string
---@field api_type string|nil
---@field auth_method "basic"|"bearer"|nil
---@field cache_ttl number|nil Cache lifetime in seconds. Set to 0 to disable caching.
