-- Example:
--   require("atlas").setup({
--     providers = {
--       ---@type AtlasGitLabConfig
--       gitlab = {
--         base_url = "https://gitlab.com",
--         token    = vim.env.GITLAB_TOKEN,
--         cache_ttl = 300, -- Seconds; 0 disables caching.
--       },
--     },
--     issues = {
--       ---@type AtlasGitLabIssuesConfig
--       gitlab = {
--         views = {
--           {
--             name = "Assigned",
--             key = "1",
--             layout = "compact", -- "compact" or "plain".
--             scope = "assigned_to_me",
--             state = "opened", -- "opened", "closed", or "all".
--             -- current_repo = true, -- Local repository; alternative to project.
--             -- project = "group/project", -- Project path or numeric ID.
--             -- labels = "bug,backend",
--             -- milestone = "v1.0",
--             -- assignee_username = "your-user",
--             -- author_username = "your-user",
--             -- search = "fix",
--             -- order_by = "updated_at",
--             -- sort = "desc", -- "asc" or "desc".
--             -- extra_params = { ["not[labels]"] = "wontfix" },
--           },
--           { name = "Created",  key = "2", scope = "created_by_me",  state = "opened" },
--           { name = "All open", key = "3", scope = "all",            state = "opened" },
--         },
--         bookmarks = {
--           -- key   = "S",      -- default
--           -- label = "Search", -- default
--           items = {
--             ["No labels"] = { layout = "compact", scope = "all", state = "opened",
--                               extra_params = { ["not[labels]"] = "*" } },
--             ["Closed"]    = { scope = "created_by_me", state = "closed" },
--           },
--         },
--       },
--     },
--   })
--
-- View options map directly to GitLab API:
--   scope:    "created_by_me" | "assigned_to_me" | "all"
--   state:    "opened" | "closed" | "all"
--   labels, milestone, assignee_username, author_username, search
--   order_by: "created_at" | "updated_at" | "priority" | ...
--   sort:     "asc" | "desc"
--
-- Anything not covered above can be passed via `extra_params = { key = "value", ... }`.

---@class AtlasGitLabIssuesSearchConfig
---@field scope string|nil
---@field project string|number|nil
---@field state "opened"|"closed"|"all"|nil
---@field labels string|nil
---@field milestone string|nil
---@field assignee_username string|nil
---@field author_username string|nil
---@field search string|nil
---@field sort "asc"|"desc"|nil
---@field order_by string|nil
---@field extra_params table<string, string>|nil

---@class AtlasGitLabIssuesViewConfig : IssuesViewConfig, AtlasGitLabIssuesSearchConfig
---@field current_repo boolean|nil

---@class AtlasGitLabIssuesBookmarkConfig : AtlasIssuesBookmarkConfig, AtlasGitLabIssuesSearchConfig

---@class AtlasGitLabIssuesBookmarksConfig
---@field key string|nil    -- default "S"
---@field label string|nil  -- default "Search"
---@field items table<string, AtlasGitLabIssuesBookmarkConfig>|nil

---@class AtlasGitLabIssuesConfig
---@field views AtlasGitLabIssuesViewConfig[]|nil
---@field bookmarks AtlasGitLabIssuesBookmarksConfig|nil
