-- Example:
--   require("atlas").setup({
--     providers = {
--       ---@type AtlasGitLabConfig
--       gitlab = {
--         base_url = "https://gitlab.com",
--         token    = vim.env.GITLAB_TOKEN,
--         cache_ttl = 300, -- Seconds; 0 disables caching.
--         -- CI options: https://github.com/emrearmagan/atlas.nvim#pipeline-configuration
--       },
--     },
--     pulls = {
--       ---@type AtlasGitLabPullsConfig
--       gitlab = {
--         views = {
--           {
--             name = "Assigned",
--             key = "1",
--             layout = "compact", -- "compact", "grouped", or "plain".
--             scope = "assigned_to_me",
--             -- current_repo = true, -- Local repository; alternative to project/group.
--             -- project = "group/project", -- Project path or numeric ID.
--             -- group = "group", -- Group path or numeric ID.
--             -- labels = "bug,backend",
--             -- milestone = "v1.0",
--             -- assignee_username = "your-user",
--             -- author_username = "your-user",
--             -- search = "fix",
--             -- order_by = "updated_at",
--             -- sort = "desc", -- "asc" or "desc".
--             -- extra_params = { target_branch = "main" },
--           },
--           { name = "Created",   key = "2", scope = "created_by_me" },
--           { name = "Reviewing", key = "3", scope = "reviews_for_me" },
--         },
--         bookmarks = {
--           -- key   = "S",      -- default
--           -- label = "Search", -- default
--           items = {
--             ["Reviewing"]   = { layout = "compact", scope = "reviews_for_me" },
--             ["Created by me"] = { scope = "all", author_username = "me" },
--           },
--         },
--       },
--     },
--   })
--
-- View options map directly to GitLab API:
--   scope:    "created_by_me" | "assigned_to_me" | "reviews_for_me" | "all"
--   labels, milestone, assignee_username, author_username, search
--   order_by: "created_at" | "updated_at" | "title" | ...
--   sort:     "asc" | "desc"
--
-- Anything not covered above can be passed via `extra_params = { key = "value", ... }`.
-- TODO: It should work in theory, but i have not tested it yet...

---@class AtlasGitLabPullsSearchConfig
---@field scope string|nil
---@field project string|number|nil
---@field group string|number|nil
---@field labels string|nil
---@field milestone string|nil
---@field assignee_username string|nil
---@field author_username string|nil
---@field sort "asc"|"desc"|nil
---@field order_by string|nil
---@field extra_params table<string, string>|nil

---@class AtlasGitLabPullsViewConfig : AtlasPullsViewConfig, AtlasGitLabPullsSearchConfig

---@class AtlasGitLabPullsBookmarkConfig : AtlasPullsBookmarkConfig, AtlasGitLabPullsSearchConfig

---@class AtlasGitLabPullsBookmarksConfig
---@field key string|nil    -- default "S"
---@field label string|nil  -- default "Search"
---@field items table<string, AtlasGitLabPullsBookmarkConfig>|nil

---@class AtlasGitLabPullsConfig
---@field views AtlasGitLabPullsViewConfig[]|nil
---@field bookmarks AtlasGitLabPullsBookmarksConfig|nil
